# Generated by Django 4.1.7 on 2023-03-07 14:01

from django.db import migrations, models

def add_column(apps, schema_editor):
    Score = apps.get_model('myapp', 'Score')
    db_alias = schema_editor.connection.alias
    Score._meta.db_table = 'myapp_Score'
    schema_editor.execute("ALTER TABLE myapp_Score ADD COLUMN new_column varchar(255);")

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE myapp_Score ADD COLUMN new_column varchar(255) DEFAULT 'add success';",
            "ALTER TABLE myapp_Score DROP COLUMN new_column;"
        )
    ]

