# Generated by Django 4.1.7 on 2023-03-07 14:01

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_column'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE myapp_Score DROP COLUMN new_column;",
            "ALTER TABLE myapp_Score ADD COLUMN new_column varchar(255) DEFAULT 'add success';"
        )
    ]
